export const SITE_CONFIG = {
  name: "Lords of Lending",
  tagline: "Purveyors of Honest Capital",
  description:
    "Lords of Lending connects small businesses with SBA loans and funding. Expert help, clear steps, and fast approvals to fuel your business growth.",
  url: "https://lordsoflending.com",
  email: "shane@lordsoflending.com",
  linkedin: "https://www.linkedin.com/company/lords-of-lending",
  youtube: "https://www.youtube.com/@LordsofLending",
  rss: "https://feeds.buzzsprout.com/2315806.rss",
  loanAppUrl: "/loans/loan-application",
} as const;

export const NAV_LINKS = [
  { label: "Brokers", href: "/brokers" },
  { label: "Blog", href: "/blog" },
  { label: "Podcast", href: "/podcast" },
  { label: "Learn", href: "https://learn.lordsoflending.com", external: true, glow: true },
  { label: "Contact", href: "/contact" },
] as const;

export const TEAM = [
  {
    name: "Shane Pierson",
    title: "Founder",
    bankTitle: "SBA National Sales Manager",
    phone: "805-551-7184",
    email: "shane@lordsoflending.com",
    bankEmail: "spierson@communitybankshares.com",
    headshot: "/images/headshots/shane-pierson.webp",
    booking:
      "https://outlook.office.com/bookwithme/user/ae91cc1223e04264968da1fde99c4e35@communitybankshares.com/meetingtype/qeaRhrmQU0qOFpNOL63ZVQ2?anonymous&ep=mcard",
  },
  {
    name: "Stephanie Castagnier Dunn",
    title: "Founder",
    bankTitle: "EVP Chief SBA Revenue Officer",
    phone: "847-477-7546",
    email: "steph@lordsoflending.com",
    bankEmail: "sdunn@communitybankshares.com",
    headshot: "/images/headshots/stephanie-dunn.webp",
    booking:
      "https://outlook.office.com/bookwithme/user/537429cac454431c94eb1185d210705d@communitybankshares.com?anonymous&ep=pcard",
  },
  {
    name: "Brian Congelliere",
    title: "Founder",
    bankTitle: "VP SBA Business Development Officer",
    phone: "805-807-7080",
    email: "brian@lordsoflending.com",
    bankEmail: "bcongelliere@communitybankshares.com",
    headshot: "/images/headshots/brian-congelliere.webp",
    booking:
      "https://outlook.office.com/bookwithme/user/ee18c77d1eb64e12bfd7da52508fd7fb@communitybankshares.com?anonymous&ep=pcard",
  },
] as const;

export const STATS = [
  { value: "$450+", label: "Million", description: "in funding delivered" },
  { value: "425+", label: "Businesses", description: "funded nationwide" },
  { value: "55+", label: "Years", description: "of lending expertise" },
] as const;

export const PROGRAM_BASICS = [
  "Loans up to 5 million, nationwide",
  "Up to 90% financing on business acquisitions",
  "Up to 100%+ LTV on real estate purchases and refinances",
  "Loan Terms from 10 to 25 years",
  "Rates from WSJ Prime +1% to 3%",
  "Funding in 45 to 60 days",
  "Referral fee schedule provided upon request",
  "Business debt consolidation and working capital loans",
] as const;

export const ELIGIBLE_USES = [
  { label: "Acquisition & Expansion", icon: "/images/icons/expansion.png" },
  { label: "Construction Loans", icon: "/images/icons/construction.png" },
  { label: "Partner Buyout", icon: "/images/icons/buyout.png" },
  { label: "Succession Planning", icon: "/images/icons/plan.png" },
  { label: "Refinance Business Debt", icon: "/images/icons/refi.png" },
] as const;

export const REQUIRED_DOCS = [
  { text: "Completed loan application", conditional: false },
  { text: "Last 3 years business tax returns", conditional: false },
  { text: "YTD business financials", conditional: false },
  { text: "Business debt schedule", conditional: false },
  { text: "Last 3 years personal tax returns", conditional: false },
  { text: "Purchase agreement", conditional: true },
  { text: "Copies of notes to be refinanced", conditional: true },
  { text: "Business plan", conditional: true },
] as const;

export const PORTFOLIO_LOGOS = [
  { name: "A1A Surveying Services", image: "/images/portfolio/a1a-surveying.png", url: "https://www.a1asurveying.com/" },
  { name: "Artificial Grass Liquidators", image: "/images/portfolio/agl.webp" },
  { name: "Faithful Heritage Holdings", image: "/images/portfolio/fhh.webp", url: "https://faithfulheritageholdings.com/" },
  { name: "Hampton by Hilton", image: "/images/portfolio/hampton.png" },
  { name: "Linkflow", image: "/images/portfolio/linkflow.webp" },
  { name: "Blue Edge", image: "/images/portfolio/blue-edge.png" },
  { name: "FedEx Routes", image: "/images/portfolio/fedex.png" },
  { name: "glo", image: "/images/portfolio/glo.png" },
  { name: "Unite Digital", image: "/images/portfolio/unite-digital.png" },
  { name: "Wireless Buybacks", image: "/images/portfolio/wireless-buybacks.png" },
  { name: "Choice Hotels", image: "/images/portfolio/choice-hotels.png" },
  { name: "Belmar Lanes", image: "/images/portfolio/belmar-lanes.png" },
  { name: "Ruth's Chris", image: "/images/portfolio/ruths-chris.webp" },
  { name: "Zelectric", image: "/images/portfolio/zelectric.png" },
] as const;

export const TESTIMONIALS = [
  {
    quote:
      "Not only did [Shane] provide professional and very prompt service/feedback, but also offered reassurance and solutions when we encountered roadblocks that seemed almost impossible to navigate through. I have to truly say he went above and beyond his duties to see the acquisition to the end and I can't recommend his services enough!",
    name: "Shawn Kleotzer",
    title: "Owner and President",
    company: "A1A Surveying Services",
    image: "/images/portfolio/a1a-surveying.png",
    personImage: "/images/testimonials/shawn-kleotzer.png",
    url: "https://www.a1asurveying.com/",
  },
  {
    quote:
      "Stephany is the most knowledgeable banker I have used! I have done 5 SBA loans with her. [If] you call her, she is always ready to help and guide you through every point of the process. When you have the right person, it makes the loan process so easy. Stephany is that person\u2026 She is on your side! You don\u2019t get that personalized treatment anywhere else.",
    name: "Ruth Thornquest",
    title: "CEO",
    company: "Faithful Heritage Holdings",
    image: "/images/portfolio/fhh.webp",
    personImage: "/images/testimonials/ruth-thornquest.webp",
    url: "https://faithfulheritageholdings.com/",
  },
] as const;

export const PODCAST_SUBSCRIBE_LINKS = [
  { platform: "Apple Podcasts", url: "https://podcasts.apple.com/podcast/id1798717410", color: "bg-[var(--color-dark)]" },
  { platform: "Spotify", url: "https://open.spotify.com/show/6P25i3rDng6aMqlijl9imE", color: "bg-[#1DB954]" },
  { platform: "YouTube", url: "https://www.youtube.com/playlist?list=PL3dbCeEWNxdP97JpS_-RcHy2gDFTFtG5J", color: "bg-[#FF0000]" },
  { platform: "Amazon Music", url: "https://music.amazon.com/podcasts/8a74a550-e1ac-47e5-ac1f-c4e735b51b83", color: "bg-[#25d1da]" },
  { platform: "iHeartRadio", url: "https://www.iheart.com/podcast/269-lords-of-lending-269030265/", color: "bg-[#C6002B]" },
  { platform: "Overcast", url: "https://overcast.fm/itunes1798717410", color: "bg-[#FC7E0F]" },
] as const;

export const FAQ = [
  {
    q: "Is Lords of Lending a bank or SBA lender?",
    a: "No. Lords of Lending is not a bank, credit union, or SBA lender. We are a platform that connects you directly with an SBA 7(a) lending team.",
  },
  {
    q: "What does Lords of Lending do?",
    a: "We provide education, tools, and a direct connection to an experienced SBA 7(a) lender who can guide you through the loan process\u2014from prequalification to closing.",
  },
  {
    q: "Who actually funds my SBA 7(a) loan?",
    a: "Your loan is underwritten, approved, and funded by an SBA-authorized lender that we connect you with\u2014not by Lords of Lending.",
  },
  {
    q: "Why use Lords of Lending instead of going directly to a bank?",
    a: "We simplify the process, ensure your application is fully prepared, and match you with a lender who specializes in SBA 7(a) loans for your type of business and transaction.",
  },
  {
    q: "Do you charge for connecting me to a lender?",
    a: "No. There\u2019s no upfront cost to use the Lords of Lending portal. If your loan closes, the lender compensates us for introducing and preparing the deal.",
  },
] as const;

export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  image: string;
  category: "blog" | "podcast";
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "what-to-do-if-you-cant-pay-your-business-loan",
    title: "What to Do If You Can\u2019t Pay Your Business Loan",
    date: "2025-07-09",
    excerpt: "Struggling with loan payments? Learn how to restructure, refinance, or negotiate your way out of a tough spot.",
    image: "/images/blog/cant-pay-loan.webp",
    category: "blog",
  },
  {
    slug: "sba-business-acquisition-what-lenders-really-expect",
    title: "How to Buy a Business with an SBA Loan",
    date: "2025-07-09",
    excerpt: "Learn how to finance a business purchase with an SBA loan and what lenders really look for.",
    image: "/images/blog/lenders-expect.webp",
    category: "blog",
  },
  {
    slug: "business-loans-with-bad-credit-what-you-need-to-know",
    title: "Business Loans with Bad Credit: What You Need to Know",
    date: "2025-07-08",
    excerpt: "Bad credit doesn\u2019t mean no funding\u2014but it does mean tougher terms. Here\u2019s how to navigate it.",
    image: "/images/blog/bad-credit.webp",
    category: "blog",
  },
  {
    slug: "5-myths-about-sba-loans-every-founder-should-know",
    title: "5 Myths About SBA Loans Every Founder Should Know",
    date: "2025-07-08",
    excerpt: "Think SBA loans are fast, easy, or backed by the government? Think again.",
    image: "/images/blog/five-myths.webp",
    category: "blog",
  },
  {
    slug: "why-startups-get-denied-loans-and-what-to-do-instead",
    title: "Why Startups Get Denied Loans\u2014and What to Do Instead",
    date: "2025-07-08",
    excerpt: "Most startups can\u2019t get loans because banks fund traction, not ideas. Here\u2019s what to do.",
    image: "/images/blog/startups-denied.webp",
    category: "blog",
  },
  {
    slug: "what-is-my-business-worth-a-step-by-step-valuation-guide-for-small-business-owners",
    title: "What Is My Business Worth? A Simple Valuation Guide",
    date: "2025-06-30",
    excerpt: "Learn how to calculate your business\u2019s value using real-world methods that buyers and lenders trust.",
    image: "/images/blog/business-worth.webp",
    category: "blog",
  },
  {
    slug: "the-lie-we-bought-why-time-management-isnt-enough-in-sba-lending",
    title: "Attention Trumps Time in SBA Lending",
    date: "2025-06-30",
    excerpt: "Efficient lenders lose deals when they focus on time over attention. Here\u2019s the shift that wins.",
    image: "/images/blog/attention-leverage.webp",
    category: "blog",
  },
  {
    slug: "100-financing-for-business-expansion",
    title: "How to Get 100% SBA Financing for Business Expansion",
    date: "2025-06-11",
    excerpt: "Learn how to qualify for 100% SBA 7(a) financing to grow your existing business.",
    image: "/images/blog/sba-financing.webp",
    category: "blog",
  },
];

export interface ContentMeta {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  image: string;
  category: "pillar" | "supporting" | "training";
  author: "shane" | "steph" | "brian";
  cluster?: "sba-basics" | "acquisition" | "originator-training" | "deal-structuring" | "industry-trends";
  keywords?: string[];
  readingTime?: number;
  lastUpdated?: string;
}

export const PILLAR_ARTICLES: ContentMeta[] = [
  {
    slug: "complete-guide-sba-7a-loans",
    title: "The Complete Guide to SBA 7(a) Loans in 2026",
    date: "2026-03-10",
    excerpt: "Everything you need to know about SBA 7(a) loans: eligibility, rates, terms, fees, and how to get approved in 2026.",
    image: "/images/pillar/complete-guide-sba-7a-loans.webp",
    category: "pillar",
    author: "steph",
    cluster: "sba-basics",
    readingTime: 24,
  },
  {
    slug: "how-to-become-sba-loan-broker",
    title: "How to Become an SBA Loan Broker in 2026",
    date: "2026-03-10",
    excerpt: "Step-by-step guide to launching your SBA loan brokerage, building lender relationships, and closing your first deals.",
    image: "/images/pillar/how-to-become-sba-loan-broker.webp",
    category: "pillar",
    author: "shane",
    cluster: "originator-training",
    readingTime: 15,
  },
  {
    slug: "sba-loan-originator-training",
    title: "SBA Loan Originator Training: The Complete Resource",
    date: "2026-03-10",
    excerpt: "The complete SBA originator training resource covering sourcing, packaging, lender matching, and deal closing.",
    image: "/images/pillar/sba-loan-originator-training.webp",
    category: "pillar",
    author: "brian",
    cluster: "originator-training",
    readingTime: 17,
  },
  {
    slug: "sba-deal-structuring-guide",
    title: "SBA Deal Structuring: From LOI to Closing",
    date: "2026-03-10",
    excerpt: "Master SBA deal structuring from letter of intent through closing, including equity injection, seller notes, and collateral.",
    image: "/images/pillar/sba-deal-structuring-guide.webp",
    category: "pillar",
    author: "brian",
    cluster: "deal-structuring",
    readingTime: 20,
  },
  {
    slug: "sba-lending-2026-outlook",
    title: "SBA Lending in 2026: What's Changed and What's Coming",
    date: "2026-03-10",
    excerpt: "SBA lending trends, policy changes, and market outlook for 2026 that every originator and borrower needs to know.",
    image: "/images/pillar/sba-lending-2026-outlook.webp",
    category: "pillar",
    author: "steph",
    cluster: "industry-trends",
    readingTime: 15,
  },
];

export const SUPPORTING_ARTICLES: ContentMeta[] = [
  // ─── Originator Articles ───────────────────────────────────────────
  {
    slug: "how-to-source-sba-loans",
    title: "How to Source SBA Loans: 12 Strategies That Work",
    date: "2026-03-10",
    excerpt: "Proven strategies for sourcing SBA loan deals, from referral partners and CPAs to digital marketing and trade shows.",
    image: "/images/supporting/how-to-source-sba-loans.webp",
    category: "supporting",
    author: "shane",
    cluster: "originator-training",
    readingTime: 13,
  },
  {
    slug: "sba-loan-packaging-checklist",
    title: "SBA Loan Packaging: The Originator's Checklist",
    date: "2026-03-10",
    excerpt: "The complete SBA loan packaging checklist originators need to submit clean, lender-ready deal packages.",
    image: "/images/supporting/sba-loan-packaging-checklist.webp",
    category: "supporting",
    author: "brian",
    cluster: "originator-training",
    readingTime: 12,
  },
  {
    slug: "sba-referral-fee-structures",
    title: "SBA Referral Fee Structures: How Brokers Get Paid",
    date: "2026-03-10",
    excerpt: "How SBA loan brokers earn referral fees, typical fee structures, and what lenders expect from originator relationships.",
    image: "/images/supporting/sba-referral-fee-structures.webp",
    category: "supporting",
    author: "shane",
    cluster: "originator-training",
    readingTime: 11,
  },
  {
    slug: "building-sba-lending-pipeline",
    title: "Building an SBA Lending Pipeline from Zero",
    date: "2026-03-10",
    excerpt: "How to build a consistent SBA lending pipeline from scratch using relationship-driven and digital strategies.",
    image: "/images/supporting/building-sba-lending-pipeline.webp",
    category: "supporting",
    author: "shane",
    cluster: "originator-training",
    readingTime: 13,
  },
  {
    slug: "matching-borrowers-sba-lenders",
    title: "How to Match Borrowers with the Right SBA Lender",
    date: "2026-03-10",
    excerpt: "Learn how to match SBA borrowers with the right lender based on deal size, industry, geography, and risk appetite.",
    image: "/images/supporting/matching-borrowers-sba-lenders.webp",
    category: "supporting",
    author: "steph",
    cluster: "originator-training",
    readingTime: 11,
  },
  {
    slug: "sba-originator-tech-stack",
    title: "The SBA Originator's Tech Stack",
    date: "2026-03-10",
    excerpt: "The essential CRM, document management, and communication tools every SBA loan originator needs to scale.",
    image: "/images/supporting/sba-originator-tech-stack.webp",
    category: "supporting",
    author: "brian",
    cluster: "originator-training",
    readingTime: 6,
  },
  {
    slug: "sba-convention-networking",
    title: "SBA Convention Season: How to Network and Win Deals",
    date: "2026-03-10",
    excerpt: "How to maximize SBA industry conferences, build lender relationships, and turn convention contacts into closed deals.",
    image: "/images/supporting/sba-convention-networking.webp",
    category: "supporting",
    author: "shane",
    cluster: "originator-training",
    readingTime: 5,
  },
  {
    slug: "bank-bdo-to-independent",
    title: "From Bank BDO to Independent Originator",
    date: "2026-03-10",
    excerpt: "How bank business development officers transition to independent SBA loan origination and build their own book.",
    image: "/images/supporting/bank-bdo-to-independent.webp",
    category: "supporting",
    author: "shane",
    cluster: "originator-training",
    readingTime: 6,
  },
  // ─── Borrower Articles ─────────────────────────────────────────────
  {
    slug: "sba-7a-vs-504",
    title: "SBA 7(a) vs. SBA 504: Which Loan Is Right for You?",
    date: "2026-03-10",
    excerpt: "Compare SBA 7(a) and SBA 504 loans side by side to find the right program for your business needs.",
    image: "/images/supporting/sba-7a-vs-504.webp",
    category: "supporting",
    author: "steph",
    cluster: "sba-basics",
    readingTime: 8,
  },
  {
    slug: "sba-application-checklist",
    title: "SBA Loan Application Checklist: Every Document You Need",
    date: "2026-03-10",
    excerpt: "The complete document checklist for SBA loan applications, from tax returns to business plans and financial statements.",
    image: "/images/supporting/sba-application-checklist.webp",
    category: "supporting",
    author: "brian",
    cluster: "sba-basics",
    readingTime: 6,
  },
  {
    slug: "how-long-sba-loan-takes",
    title: "How Long Does an SBA Loan Take? Real Timelines",
    date: "2026-03-10",
    excerpt: "Realistic SBA loan timelines from application to funding, with tips to speed up the approval process.",
    image: "/images/supporting/how-long-sba-loan-takes.webp",
    category: "supporting",
    author: "shane",
    cluster: "sba-basics",
    readingTime: 8,
  },
  {
    slug: "sba-down-payment",
    title: "SBA Loan Down Payment: How Much Do You Really Need?",
    date: "2026-03-10",
    excerpt: "Understand SBA loan down payment requirements, equity injection rules, and strategies to reduce your cash at closing.",
    image: "/images/supporting/sba-down-payment.webp",
    category: "supporting",
    author: "steph",
    cluster: "sba-basics",
    readingTime: 9,
  },
  {
    slug: "buy-business-sba-loan",
    title: "Can You Use an SBA Loan to Buy a Business?",
    date: "2026-03-10",
    excerpt: "How to use SBA 7(a) loans to buy an existing business, including acquisition requirements and deal structuring.",
    image: "/images/supporting/buy-business-sba-loan.webp",
    category: "supporting",
    author: "shane",
    cluster: "acquisition",
    readingTime: 10,
  },
  {
    slug: "sba-loan-denied",
    title: "SBA Loan Denial: Why It Happens and What to Do Next",
    date: "2026-03-10",
    excerpt: "Common reasons SBA loans get denied, how to fix your application, and alternative paths to business funding.",
    image: "/images/supporting/sba-loan-denied.webp",
    category: "supporting",
    author: "shane",
    cluster: "sba-basics",
    readingTime: 9,
  },
  {
    slug: "sba-loan-fees",
    title: "Understanding SBA Loan Fees: What You'll Actually Pay",
    date: "2026-03-10",
    excerpt: "A complete breakdown of SBA loan fees including guarantee fees, packaging fees, and closing costs borrowers should expect.",
    image: "/images/supporting/sba-loan-fees.webp",
    category: "supporting",
    author: "brian",
    cluster: "sba-basics",
    readingTime: 9,
  },
  {
    slug: "sba-loans-veterans",
    title: "SBA Loans for Veterans: Benefits and Programs",
    date: "2026-03-10",
    excerpt: "SBA loan programs, fee waivers, and resources available to veteran business owners and military entrepreneurs.",
    image: "/images/supporting/sba-loans-veterans.webp",
    category: "supporting",
    author: "steph",
    cluster: "sba-basics",
    readingTime: 8,
  },
  // ─── Thought Leadership ────────────────────────────────────────────
  {
    slug: "why-sba-deals-fall-apart",
    title: "Why Most SBA Deals Fall Apart (And How to Save Them)",
    date: "2026-03-10",
    excerpt: "The top reasons SBA deals collapse before closing and practical strategies originators use to rescue them.",
    image: "/images/supporting/why-sba-deals-fall-apart.webp",
    category: "supporting",
    author: "shane",
    cluster: "deal-structuring",
    readingTime: 10,
  },
  {
    slug: "future-sba-lending",
    title: "The Future of SBA Lending: AI, Fintech, and the Human Touch",
    date: "2026-03-10",
    excerpt: "How AI, fintech platforms, and automation are reshaping SBA lending while relationships remain the core of deals.",
    image: "/images/supporting/future-sba-lending.webp",
    category: "supporting",
    author: "brian",
    cluster: "industry-trends",
    readingTime: 9,
  },
  {
    slug: "coleman-report-insights",
    title: "What the Coleman Report Won't Tell You About SBA Lending",
    date: "2026-03-10",
    excerpt: "Insights beyond the Coleman Report data that reveal what's really happening in the SBA lending market.",
    image: "/images/supporting/coleman-report-insights.webp",
    category: "supporting",
    author: "steph",
    cluster: "industry-trends",
    readingTime: 8,
  },
  {
    slug: "sba-lending-myths-originators",
    title: "SBA Lending Myths That Cost Originators Deals",
    date: "2026-03-10",
    excerpt: "Debunking the most common SBA lending myths that cause originators to lose deals and damage lender relationships.",
    image: "/images/supporting/sba-lending-myths-originators.webp",
    category: "supporting",
    author: "shane",
    cluster: "originator-training",
    readingTime: 10,
  },
  // ─── Training Articles ─────────────────────────────────────────────
  {
    slug: "sba-lending-101-foundation",
    title: "SBA Lending 101: The Foundation Every Originator Needs",
    date: "2026-03-10",
    excerpt: "The foundational SBA lending knowledge every new originator needs, from program basics to lender expectations.",
    image: "/images/supporting/sba-lending-101-foundation.webp",
    category: "training",
    author: "shane",
    cluster: "sba-basics",
    readingTime: 8,
  },
  {
    slug: "sba-eligibility-deep-dive",
    title: "SBA Eligibility Deep Dive: Who Really Qualifies?",
    date: "2026-03-10",
    excerpt: "A deep dive into SBA loan eligibility requirements, size standards, and the nuances that trip up most applicants.",
    image: "/images/supporting/sba-eligibility-deep-dive.webp",
    category: "training",
    author: "brian",
    cluster: "sba-basics",
    readingTime: 9,
  },
  {
    slug: "sba-fee-structures-explained",
    title: "SBA Fee Structures Explained: The Complete Breakdown for Originators",
    date: "2026-03-10",
    excerpt: "Complete breakdown of SBA guarantee fees, servicing fees, and originator compensation structures.",
    image: "/images/supporting/sba-fee-structures-explained.webp",
    category: "training",
    author: "brian",
    cluster: "originator-training",
    readingTime: 9,
  },
  {
    slug: "how-to-read-borrower-financials",
    title: "How to Read a Borrower's Financials Like a Pro",
    date: "2026-03-10",
    excerpt: "Learn to analyze borrower financial statements, spot red flags, and assess creditworthiness like an experienced underwriter.",
    image: "/images/supporting/how-to-read-borrower-financials.webp",
    category: "training",
    author: "brian",
    cluster: "deal-structuring",
    readingTime: 11,
  },
  {
    slug: "art-of-sba-deal-structuring",
    title: "The Art of SBA Deal Structuring: What Separates Good from Great",
    date: "2026-03-10",
    excerpt: "Advanced SBA deal structuring techniques that separate top originators from the rest of the pack.",
    image: "/images/supporting/art-of-sba-deal-structuring.webp",
    category: "training",
    author: "brian",
    cluster: "deal-structuring",
    readingTime: 7,
  },
  {
    slug: "complete-sba-documentation-checklist",
    title: "The Complete SBA Documentation Checklist",
    date: "2026-03-10",
    excerpt: "Every document an SBA originator needs to collect, organize, and submit for a clean loan package.",
    image: "/images/supporting/complete-sba-documentation-checklist.webp",
    category: "training",
    author: "brian",
    cluster: "originator-training",
    readingTime: 7,
  },
  {
    slug: "build-10m-sba-pipeline",
    title: "How to Build a $10M SBA Pipeline in 12 Months",
    date: "2026-03-10",
    excerpt: "A month-by-month playbook for building a $10 million SBA lending pipeline from scratch in your first year.",
    image: "/images/supporting/build-10m-sba-pipeline.webp",
    category: "training",
    author: "shane",
    cluster: "originator-training",
    readingTime: 7,
  },
  {
    slug: "building-sba-brokerage",
    title: "Building an SBA Brokerage: From Solo to Scale",
    date: "2026-03-10",
    excerpt: "How to grow from a solo SBA originator to a scalable brokerage with systems, hiring, and lender diversification.",
    image: "/images/supporting/building-sba-brokerage.webp",
    category: "training",
    author: "shane",
    cluster: "originator-training",
    readingTime: 8,
  },
];

export const PODCAST_EPISODES = [
  { slug: "why-equity-not-cash-flow-makes-or-breaks-sba-deals-lol-20", title: "Why Equity (Not Cash Flow) Makes or Breaks SBA Deals | LoL #20", date: "2026-03-04", excerpt: "Former SBA deputy director Lance Sexton reveals why equity injection—not cash flow—is the #1 deal killer, and what happens when thin deals go to liquidation.", buzzsproutId: "TBD-20" },
  { slug: "the-year-of-discipline-lol-19", title: "The Year of Discipline | LoL #19", date: "2026-02-18", excerpt: "2026 is the year of discipline. The Lords break down why thin deals are dying, equity injection matters more than ever, and ownership must be earned.", buzzsproutId: "TBD-19" },
  { slug: "2026-look-ahead-and-prediction-lol-18", title: "2026 Look Ahead and Predictions | LoL #18", date: "2026-02-04", excerpt: "Economic forecast for small businesses in 2026, increased borrowing, and reduced equity trends.", buzzsproutId: "18585787" },
  { slug: "2025-lessons-and-reflections-lol-17", title: "2025 Lessons and Reflections | LoL #17", date: "2026-01-28", excerpt: "What happens when a business owner drops hints about selling\u2014or buying.", buzzsproutId: "18585460" },
  { slug: "when-a-business-owner-asks-you-to-dance-lol-16", title: "When a Business Owner Asks You to Dance | LoL #16", date: "2025-10-08", excerpt: "Reading signals from business owners and navigating the dance of deal-making.", buzzsproutId: "17977047" },
  { slug: "seller-notes-deep-dive-lol-15", title: "Seller Notes Deep Dive | LoL #15", date: "2025-10-03", excerpt: "Deep dive on seller notes, liquidity, and smarter deal structuring.", buzzsproutId: "17947301" },
  { slug: "building-a-successful-restaurant-lol-14", title: "Building a Successful Restaurant | LoL #14", date: "2025-09-10", excerpt: "Real-world challenges, margins, and lending strategies for restaurant acquisitions.", buzzsproutId: "17819497" },
  { slug: "do-interest-rates-really-matter-lol-13", title: "Do Interest Rates Really Matter? | LoL #13", date: "2025-09-03", excerpt: "How business owners can build trust and credibility through lending relationships.", buzzsproutId: "17772477" },
  { slug: "reputation-with-stuart-faught-lol-12", title: "Reputation with Stuart Faught | LoL #12", date: "2025-08-21", excerpt: "Building trust and credibility through real-world business experience.", buzzsproutId: "17711628" },
  { slug: "ask-the-experts-lol-11", title: "Ask the Experts | LoL #11", date: "2025-08-14", excerpt: "Shane, Stephanie, and Brian answer listener questions about SBA lending.", buzzsproutId: "17667713" },
  { slug: "ennobled-by-fire-lol-10", title: "Ennobled by Fire | LoL #10", date: "2025-06-25", excerpt: "The defining struggles that forged the Lords of Lending team.", buzzsproutId: "17355069" },
  { slug: "acquisition-war-room-lol-9", title: "Acquisition War Room | LoL #9", date: "2025-06-18", excerpt: "From trade shows to takeaways\u2014how lenders can use AI and strategy.", buzzsproutId: "17355014" },
  { slug: "insights-from-the-road-lol-8", title: "Insights from the Road | LoL #8", date: "2025-05-21", excerpt: "Field insights from lenders navigating real deals on the ground.", buzzsproutId: "17199145" },
  { slug: "meet-your-lords-lol-7", title: "Meet Your Lords | LoL #7", date: "2025-05-07", excerpt: "Meet the minds behind Lords of Lending\u2014Shane, Stephanie & Brian.", buzzsproutId: "17112379" },
  { slug: "bomb-goes-off-on-sba-lol-6", title: "Bomb Goes Off on SBA | LoL #6", date: "2025-04-30", excerpt: "SBA changes shake small business lending\u2014the Lords break it down.", buzzsproutId: "17067883" },
  { slug: "broke-or-billionaire-by-2030-lol-5", title: "Broke or Billionaire by 2030 | LoL #5", date: "2025-04-15", excerpt: "Bold predictions and wealth-building strategies for entrepreneurs.", buzzsproutId: "16900509" },
  { slug: "buying-and-scaling-a-business-lol-4", title: "Buying and Scaling a Business | LoL #4", date: "2025-04-01", excerpt: "How to acquire and scale a business with SBA financing.", buzzsproutId: "16818617" },
  { slug: "you-are-not-urgent-enough-lol-3", title: "You Are Not Urgent Enough | LoL #3", date: "2025-03-15", excerpt: "Why urgency is the missing ingredient in most lending pipelines.", buzzsproutId: "16776392" },
  { slug: "podcast-lets-talk-tariffs", title: "Let\u2019s Talk Tariffs", date: "2025-03-01", excerpt: "How tariffs impact small businesses and lending decisions.", buzzsproutId: "16691774" },
  { slug: "the-rise-of-automated-lending", title: "The Rise of Automated Lending", date: "2025-02-15", excerpt: "AI, fintech, and the future of small business lending.", buzzsproutId: "16732507" },
];
